---
apiVersion: v1
kind: Service
metadata:
  name: app1-service-code
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 7000
    nodePort: 30002
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: kubernetes_examples/app1:local
        ports:
        - containerPort: 7000
